#!/usr/bin/env bash
# =============================================================================
# SentryCLI - CMS Detection Module
# Detects WordPress, Joomla, Drupal, Shopify, Magento, etc.
# =============================================================================

run_cmsdetect() {

    print_section "46. CMS DETECTION"

    local target=""

    # Get target from REPL
    if [[ -n "${MODULE_OPTS[target]:-}" ]]; then
        target="${MODULE_OPTS[target]}"
        print_info "Using target → ${target}"
    elif [[ -n "${MODULE_OPTS[host]:-}" ]]; then
        target="${MODULE_OPTS[host]}"
    elif [[ -n "$1" ]]; then
        target="$1"
    fi

    # Interactive input
    if [[ -z "$target" ]]; then
        echo -ne "${CYAN}Enter Target Domain/URL: ${RESET}"
        read -r target
    fi

    [[ -z "$target" ]] && { print_alert "No target provided."; return 1; }

    # Add https:// if missing
    if [[ ! "$target" =~ ^https?:// ]]; then
        target="https://${target}"
    fi

    # Report file
    local report_dir="${SENTRYCLI_ROOT:-.}/reports"
    mkdir -p "$report_dir"
    local report="${report_dir}/CMS_Detection_${target//https:\/\//}_$(date '+%Y%m%d_%H%M%S').txt"

    print_subsection "Analyzing CMS on → ${target}"
    echo ""

    print_info "Sending detection probes..."

    # ── Main Detection Logic ───────────────────────────────────────────────
    local cms_found="None"
    local version="Unknown"
    local confidence=0

    # Check common CMS fingerprints
    local headers body

    headers=$(curl -s -I -L --max-time 12 "$target")
    body=$(curl -s -L --max-time 15 "$target")

    # WordPress Detection
    if echo "$body" | grep -qiE 'wp-content|wp-includes|wordpress'; then
        cms_found="WordPress"
        confidence=90
        version=$(echo "$body" | grep -oE 'wp-emoji-release.min.js\?ver=[0-9.]+' | cut -d'=' -f2 | head -n1)
    fi

    # Joomla Detection
    if echo "$headers $body" | grep -qiE 'joomla|Joomla'; then
        cms_found="Joomla"
        confidence=85
    fi

    # Drupal Detection
    if echo "$headers $body" | grep -qiE 'drupal|Drupal'; then
        cms_found="Drupal"
        confidence=80
    fi

    # Shopify Detection
    if echo "$headers" | grep -qi "x-shopid\|shopify"; then
        cms_found="Shopify"
        confidence=95
    fi

    # Magento Detection
    if echo "$body" | grep -qiE 'mage|Magento'; then
        cms_found="Magento"
        confidence=75
    fi

    # Laravel / PHP Framework
    if echo "$headers" | grep -qi "laravel"; then
        cms_found="Laravel (PHP Framework)"
        confidence=70
    fi

    # Fallback - Generic
    if [[ "$cms_found" == "None" ]]; then
        if echo "$headers" | grep -qi "powered-by"; then
            cms_found="Custom / Unknown (Powered-By header found)"
            confidence=40
        else
            cms_found="Unknown / Static HTML"
            confidence=30
        fi
    fi

    # ── Display Results ─────────────────────────────────────────────────────
    echo ""
    echo -e "${BOLD}${WHITE}CMS DETECTION RESULTS${RESET}"
    echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"

    print_kv "Target" "$target"
    print_kv "Detected CMS" "$cms_found"
    print_kv "Version" "${version:-Unknown}"
    print_kv "Confidence" "${confidence}%"

    if [[ "$cms_found" != "Unknown / Static HTML" && "$cms_found" != "None" ]]; then
        print_success "   CMS Identified Successfully!"
    else
        print_warn "   Could not identify any known CMS"
    fi

    # ── Save Report ────────────────────────────────────────────────────────
    {
        echo "========================================"
        echo "         CMS DETECTION REPORT"
        echo "========================================"
        echo ""
        echo "Target          : $target"
        echo "Scan Date       : $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "----------------------------------------"
        echo ""
        echo "Detected CMS    : $cms_found"
        echo "Version         : ${version:-Unknown}"
        echo "Confidence      : ${confidence}%"
        echo ""
        echo "----------------------------------------"
        echo "Raw Headers:"
        echo "----------------------------------------"
        echo "$headers"
        echo ""
        echo "----------------------------------------"
        echo "Report generated by SentryCLI"
    } > "$report"

    echo ""
    print_success "CMS Detection completed!"
    print_success "Report saved → ${report}"

    echo ""
    echo -ne "${CYAN}Press ENTER to return to main menu...${RESET}"
    read -r

    CURRENT_MODULE=""
    MODULE_OPTS=()
}
                         
