#!/usr/bin/env bash
# =============================================================================
# SentryCLI - Directory Brute Forcer Module
# Finds hidden directories, backup files, and admin panels
# =============================================================================

run_dirbrute() {

    print_section "48. DIRECTORY BRUTE FORCER"

    local target=""
    local wordlist=""

    # Get input from REPL
    if [[ -n "${MODULE_OPTS[target]:-}" ]]; then
        target="${MODULE_OPTS[target]}"
        print_info "Target → ${target}"
    elif [[ -n "$1" ]]; then
        target="$1"
    fi

    if [[ -n "${MODULE_OPTS[wordlist]:-}" ]]; then
        wordlist="${MODULE_OPTS[wordlist]}"
    fi

    # Interactive input
    if [[ -z "$target" ]]; then
        echo -ne "${CYAN}Enter Target (e.g. example.com or https://example.com): ${RESET}"
        read -r target
    fi

    [[ -z "$target" ]] && { print_alert "No target provided."; return 1; }

    # Add https:// if not present
    if [[ ! "$target" =~ ^https?:// ]]; then
        target="https://${target}"
    fi

    # Choose wordlist
    if [[ -z "$wordlist" ]]; then
        if [[ -f "/usr/share/wordlists/dirb/common.txt" ]]; then
            wordlist="/usr/share/wordlists/dirb/common.txt"
            print_info "Using default wordlist: common.txt"
        elif [[ -f "/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt" ]]; then
            wordlist="/usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt"
            print_info "Using dirbuster wordlist"
        else
            print_warn "No wordlist found. Using small built-in list."
            wordlist=""  # Will use internal small list
        fi
    fi

    # Report file
    local report_dir="${SENTRYCLI_ROOT:-.}/reports"
    mkdir -p "$report_dir"
    local report="${report_dir}/DirBrute_${target//[^a-zA-Z0-9]/_}_$(date '+%Y%m%d_%H%M%S').txt"

    print_subsection "Starting Directory Brute Force → ${target}"
    echo ""

    # ── Run Brute Force ─────────────────────────────────────────────────────
    print_info "Scanning for hidden directories and files..."

    local scan_output=""

    if command -v gobuster &>/dev/null; then
        print_info "Using gobuster (faster)"
        scan_output=$(gobuster dir -u "$target" \
            ${wordlist:+-w "$wordlist"} \
            -q -e -k --timeout 5s 2>&1)
    elif command -v ffuf &>/dev/null; then
        print_info "Using ffuf"
        scan_output=$(ffuf -u "${target}/FUZZ" \
            ${wordlist:+-w "$wordlist"} \
            -mc 200,204,301,302,307,401,403 -silent -t 50 2>&1)
    else
        print_warn "Neither gobuster nor ffuf found. Using basic curl method (slow)"
        # Simple fallback using curl
        local common_dirs=("admin" "login" "backup" "test" "wp-admin" "phpmyadmin" ".git" "config" "uploads" "api" "dashboard")
        for dir in "${common_dirs[@]}"; do
            local status
            status=$(curl -s -o /dev/null -w "%{http_code}" -k --max-time 5 "${target}/${dir}/")
            if [[ "$status" =~ ^(200|301|302|403) ]]; then
                scan_output="${scan_output}200,301,302,403    ${target}/${dir}/\n"
            fi
        done
    fi

    # ── Save Report ────────────────────────────────────────────────────────
    {
        echo "========================================"
        echo "     DIRECTORY BRUTE FORCE REPORT"
        echo "========================================"
        echo ""
        echo "Target      : $target"
        echo "Date        : $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "Wordlist    : ${wordlist:-Built-in small list}"
        echo "----------------------------------------"
        echo ""
        echo "$scan_output"
        echo ""
        echo "----------------------------------------"
        echo "Report generated by SentryCLI"
    } > "$report"

    # ── Display Results ────────────────────────────────────────────────────
    echo ""
    echo -e "${BOLD}${WHITE}DISCOVERED DIRECTORIES / FILES${RESET}"
    echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"

    if [[ -n "$scan_output" ]] && echo "$scan_output" | grep -qE "(200|301|302|403)"; then
        echo "$scan_output" | grep -E "(200|301|302|403)" | while read -r line; do
            print_critical "  ${line}"
        done
    else
        echo -e "  ${DIM}No interesting directories or files found.${RESET}"
    fi

    # Summary
    echo ""
    echo -e "${BOLD}${WHITE}SCAN SUMMARY${RESET}"
    echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"
    print_kv "Target" "$target"
    print_kv "Wordlist" "${wordlist:-Small built-in}"
    print_kv "Report Saved" "${report}"

    echo ""
    print_success "Directory brute force completed!"
    print_success "Report saved → ${report}"

    echo ""
    echo -ne "${CYAN}Press ENTER to return to main menu...${RESET}"
    read -r

    CURRENT_MODULE=""
    MODULE_OPTS=()
}
