#!/usr/bin/env bash
# =============================================================================
# SentryCLI - Technology Stack Detector
# Detects web technologies, frameworks, CMS, servers, and libraries
# =============================================================================

run_techstack() {

    print_section "47. TECHNOLOGY STACK DETECTOR [WEB-47]"

    local target=""

    # Get target from REPL
    if [[ -n "${MODULE_OPTS[target]:-}" ]]; then
        target="${MODULE_OPTS[target]}"
        print_info "Using target → ${target}"
    elif [[ -n "${MODULE_OPTS[host]:-}" ]]; then
        target="${MODULE_OPTS[host]}"
    elif [[ -n "$1" ]]; then
        target="$1"
    fi

    # Interactive input
    if [[ -z "$target" ]]; then
        echo -ne "${CYAN}Enter Target (Domain or URL): ${RESET}"
        read -r target
    fi

    [[ -z "$target" ]] && { print_alert "No target provided."; return 1; }

    # Clean target (remove http/https)
    target=$(echo "$target" | sed -E 's|https?://||' | sed 's|/.*||')

    # Report file
    local report_dir="${SENTRYCLI_ROOT:-.}/reports"
    mkdir -p "$report_dir"
    local report="${report_dir}/TechStack_${target}_$(date '+%Y%m%d_%H%M%S').txt"

    print_subsection "Analyzing Technology Stack → ${target}"
    echo ""

    # Check for whatweb (best tool)
    if command -v whatweb &>/dev/null; then
        print_info "Using WhatWeb for advanced technology detection..."
        local tech_output
        tech_output=$(whatweb -q --color=never "https://${target}" 2>/dev/null || whatweb -q --color=never "http://${target}" 2>/dev/null)
    else
        print_warn "whatweb not found. Using basic header analysis..."
        tech_output=$(curl -s -I -L "https://${target}" 2>/dev/null || curl -s -I -L "http://${target}" 2>/dev/null)
    fi

    if [[ -z "$tech_output" ]]; then
        print_alert "Could not reach target. Check domain or internet connection."
        return 1
    fi

    # Save full report
    {
        echo "========================================"
        echo "     TECHNOLOGY STACK DETECTION REPORT"
        echo "========================================"
        echo ""
        echo "Target      : ${target}"
        echo "Scan Date   : $(date '+%Y-%m-%d %H:%M:%S %Z')"
        echo "----------------------------------------"
        echo ""
        echo "DETECTED TECHNOLOGIES:"
        echo ""
        
        if command -v whatweb &>/dev/null; then
            echo "$tech_output" | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' | sed 's/^[[:space:]]*/  /'
        else
            echo "Server:" 
            echo "$tech_output" | grep -i "^Server:" | sed 's/^/  /'
            echo ""
            echo "Other Headers:"
            echo "$tech_output" | grep -E 'X-Powered-By|X-Generator|Powered-By' | sed 's/^/  /'
        fi
        
        echo ""
        echo "----------------------------------------"
        echo "Report generated by SentryCLI"
    } > "$report"

    # ── Clean Screen Output ───────────────────────────────────────────────
    echo ""
    echo -e "${BOLD}${WHITE}DETECTED TECHNOLOGIES${RESET}"
    echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"

    if command -v whatweb &>/dev/null; then
        echo "$tech_output" | sed 's/\x1B\[[0-9;]*[a-zA-Z]//g' | sed 's/^[[:space:]]*/  /'
    else
        echo "$tech_output" | grep -E 'Server:|X-Powered-By|X-Generator|Powered-By' | sed 's/^/  /'
        echo -e "${DIM}  (Install whatweb for better results: sudo apt install whatweb)${RESET}"
    fi

    echo ""
    echo -e "${BOLD}${WHITE}SUMMARY${RESET}"
    echo -e "${CYAN}────────────────────────────────────────────────────────────${RESET}"
    print_kv "Target" "$target"
    print_kv "Report Saved" "${report}"

    if command -v whatweb &>/dev/null; then
        print_success "Technology stack analysis completed successfully!"
    else
        print_warn "Basic analysis completed (whatweb not installed)"
    fi

    echo ""
    print_success "Report saved → ${report}"

    echo ""
    echo -ne "${CYAN}Press ENTER to return to main menu...${RESET}"
    read -r

    # Return to main menu
    CURRENT_MODULE=""
    MODULE_OPTS=()
}
